### ISSUE TITLE
Backend-sync during migration takes longer than expected

### ISSUE THREAD

**Issue by redlicha** [openvstorage/volumedriver#101]
Testing shows that volume migrations take unexpectedly long. Initial log analysis show an unexpected delay after writing out the TLog which is not observed in the normal data path.

**Comment by redlicha** [comment]
Hypothesis: the check whether all data is synced to the backend is too aggressive / expensive.

**Comment by redlicha** [comment]
Manual testing shows that making the backend-sync-check less expensive and aggressive considerably improves the time for a backend sync from > 70 secs to < 30 secs.

**Comment by redlicha** [comment]
@wimpers are the current timings acceptable?

**Comment by wimpers** [comment]
I'm a bit worried that for a 256MB buffer it takes 30s. So roughly calculated 10MB/s (2500 iops) is being pushed to the backend which seems a bit on the slow side. Based upon this for a 2GB write buffer this would take 5 minutes.

@kinvaris will setup the vPool with a more performing preset (bigger fragment size) so I assume that will help a bit.

I propose to close this ticket and create a new ticket if we still encounter issues or want it faster.

**Comment by wimpers** [comment]
@kinvaris can you test the migration with the new preset and update the ticket with the timing?

**Comment by wimpers** [comment]
Closed by PM.
