### ISSUE TITLE
ClusterRegistry should have an ip address configurable for the DTL

### ISSUE THREAD

**Issue by khenderick** [openvstorage/volumedriver#113]
ClusterRegistry should have an ip address configurable for the DTL. Currently, the ip address is shared for management, xmlrpc and DTL.

Integration ticket (contains some history): https://github.com/openvstorage/framework/issues/777

**Comment by redlicha** [comment]
After discussion with @saelbrec: 
* the XMLRPC / DTL / messaging endpoints will be made independently configurable in the ClusterRegistry as this is a rather straightforward change
* the `Manual` DTL mode will be modified to allow dynamic reconfiguration of the DTL per voldrv

**Comment by redlicha** [comment]
Fixed on dev. The changes are backward compatible, but to make use of it the framework will have to be adapted (CC @khenderick). When updating from an older version make sure to first update all volumedrivers of the cluster before adding new entries to the `ClusterRegistry`.

**Comment by redlicha** [comment]
Feature implemented.
