### ISSUE TITLE
Cannot read network_server_uri via python client

### ISSUE THREAD

**Issue by khenderick** [openvstorage/volumedriver#117]
I cannot read the network_server_uri via the python client.

```
from volumedriver.storagerouter.storagerouterclient import ClusterRegistry
from volumedriver.storagerouter.storagerouterclient import ArakoonNodeConfig
n = [ArakoonNodeConfig('MS3e65NCewtZ5v4n', '10.100.169.100', 26408)]
c = ClusterRegistry('0a04895b-4473-4e23-98ce-e2540e23ec02', 'voldrv', n)
o = c.get_node_configs()
# `print o` produces: [ClusterNodeConfig { vrouter_id: "poolMS3e65NCewtZ5v4n", host: "10.100.169.100", message_port: 26200, xmlrpc_port: 26201, failovercache_port: 26202 }]
o[0].network_server_uri
```

raises

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-7-4ff59188d049> in <module>()
----> 1 x.network_server_uri

TypeError: No Python class registered for C++ class boost::optional<youtils::Uri>
```

**Comment by redlicha** [comment]
Problem in the Python API: a converter for `boost::optional<youtils::Uri>` is actually registered, but for some yet-to-be-understood reason is not used when exposing members of that type via `boost::python`s `.def_readonly`.
A quick fix would be introducing an accessor method, but AFAIU @khenderick (correct?), this is not a blocking issue so the proper fix should be investigated.

**Comment by redlicha** [comment]
http://www.boost.org/doc/libs/1_55_0/libs/python/doc/v2/faq.html#topythonconversionfailed

> If you define custom converters [...] the `def_readonly()` and `def_readwrite()` member functions provided by `boost::python::class_` for direct access to your member data will not work as expected. This is because `def_readonly("bar", &foo::bar)` is equivalent to:
> `.add_property("bar", make_getter(&foo::bar, return_internal_reference()))`
> [...]
> In order to define return value policies compatible with the custom conversions replace `def_readonly()` and `def_readwrite()` by `add_property()`. E.g.:
> `.add_property("bar", make_getter(&foo::bar, return_value_policy<return_by_value>()),
>                          make_setter(&foo::bar, return_value_policy<return_by_value>()))`

**Comment by redlicha** [comment]
Fixed on dev. A test has been added / manual testing shows it's fixed:
```
In [2]: c = src.ClusterNodeConfig("vrouter_id", "127.0.0.1", 1234, 5678, 9012, "rdma://foo:123")

In [6]: c.network_server_uri
Out[6]: 'rdma://foo:123'

In [7]: c.vrouter_id
Out[7]: 'vrouter_id'

In [9]: c.xmlrpc_port
Out[9]: 5678
```
