### ISSUE TITLE
Limit size of DTL

### ISSUE THREAD

**Issue by pploegaert** [openvstorage/volumedriver#137]
Still to be completed according to Wim Provoost

Reference:
http://jira.openvstorage.com/browse/OVS-3024

Related voldrv tickets:
http://jira.openvstorage.com/browse/OVS-2866
http://jira.openvstorage.com/browse/OVS-3220

**Comment by wimpers** [comment]
https://github.com/openvstorage/framework/issues/1386

**Comment by wimpers** [comment]
Duplicates https://github.com/openvstorage/volumedriver/issues/251
