### ISSUE TITLE
Subpar DTL performance in RDMA/Sync mode

### ISSUE THREAD

**Issue by redlicha** [openvstorage/volumedriver#138]

**Comment by redlicha** [comment]
Possibly caused by a misconfiguration of the environment as we've seen all sorts of other issues with the Edge components: server crash while in xio, xio error messages on the client side. These disappeared after changing the MLAG config between the switches.
Retesting needed.

**Comment by redlicha** [comment]
Retesting / investigation shows that the DTL components themselves (Client + Server, tested with a standalone benchmark) show expected performance whereas when testing the whole stack, an extra latency of +/. 10 usecs is observed compared to the standalone test. Root cause still unclear.

**Comment by redlicha** [comment]
The standalone benchmark benefits from `rpoll`s busy loop (before falling back to the `poll` syscall, configurable via `/etc/rdma/rsocket/polling_time`, default is 10 us) while in the benchmark for the full stack `rpoll` ends up in `poll`.

**Comment by wimpers** [comment]
Closed by PM.
