### ISSUE TITLE
GetMetadata API call

### ISSUE THREAD

**Issue by wimpers** [openvstorage/volumedriver#146]
For the https://github.com/openvstorage/volumedriver/issues/136 the edge client needs to be able to retrieve the necessary metadata as to which ASD to contact. The volumedriver should be able to provide this info through it's API.

API call: GetMetadataForPage
Returns an mdpage with the SCOid+offset for taking a cluster as a parameter. This takes the cluster as a variable and returns the entire page.

**Comment by wimpers** [comment]
@redlicha any chance we can add this to Fargo. In that case we don't need to update the voldrv to offer the High Performance Read Mesh.

**Comment by wimpers** [comment]
@chrys, can you add the GetAPI call to the edge server? Just the voldr part is required for now. The client side will be picked up post October.

**Comment by redlicha** [comment]
To be exposed to the Edge server:
* `size_t get_cluster_multiplier()`: `ClusterMultiplier` used by the vpool
* `std::vector<ClusterLocation> get_metadata_page(VolumeHandle, ClusterAddress)`

The Edge server will in turn have to expose this to Edge clients.

**Comment by redlicha** [comment]
WRT `get_cluster_multiplier`: on second thought it's better to not encode the current state of a all volumes of a vpool having the same `ClusterMultiplier` there and to instead query it per volume:
```
volumedriver::ClusterMultiplier
get_cluster_multiplier(Handle&)
```
