### ISSUE TITLE
Excessive full MDS slave rebuilds for idle clones without snapshots

### ISSUE THREAD

**Issue by redlicha** [openvstorage/volumedriver#148]
The MDS slave uses TLogs as checkpoints. For clones it does however not fall back to the parent's TLogs which causes excessive full rebuilds of MDS slaves until the first TLog of a clone itself is on the backend.

Typically certain reconfigurations (configuring a DTL) will paper over this as they cause the current TLog to be closed and sent off to the backend.

Workaround: a TLog can be forced to the backend by creating a snapshot or by scheduling a backend sync with the Python API.

**Comment by wimpers** [comment]
@redlicha would having the framework call a backend sync as last step of the clone process fix this?

**Comment by redlicha** [comment]
@wimpers: It would work around this.
