### ISSUE TITLE
Support for proxy and voldrv on separate hosts

### ISSUE THREAD

**Issue by wimpers** [openvstorage/volumedriver#150]
As a result of https://github.com/openvstorage/framework/issues/684 : in case we want to support the scenario where the proxy and voldrv run on separate hosts more work will be required than just breaking the upstart dependency.

Currently I don't know of a use case where this would be required. We have a scrub-only proxy so that is already covered.

**Comment by redlicha** [comment]
@wimpers: this requires a FR on alba as voldrv uses a client API. IOW support for remote proxies needs to be added to the alba client lib and voldrv then has to adapt to API changes (if any).

**Comment by wimpers** [comment]
Basically it needs work from every team hence moving to home repo.
