### ISSUE TITLE
Process terminates on SIGPIPE

### ISSUE THREAD

**Issue by redlicha** [openvstorage/volumedriver#153]
```
[Fri Oct 14 21:30:32 2016] init: ovs-volumedriver_vmstor main process (3446) killed by PIPE signal
```

```
2016-10-14 21:30:31 096617 +0200 - stor-08.be-g8-4 - 3446/0x00007f2bed193700 - volumedriverfs/XMLRPCTimingWrapper - 0000000000014f59 - info - execute: Call volumePerformanceCounters took 0.051277 seconds
Fri Oct 14 21:30:31 CEST 2016 [40377]: No officially blessed alternative allocator found, using libc's allocator
Fri Oct 14 21:30:31 CEST 2016 [40377]: args: -f --config arakoon://config/ovs/vpools/2caf9de9-f9bc-4ccd-8c0b-b6ad337b5389/hosts/vmstoryjDBa8b1zXE1cHVA/config?ini=%2Fopt%2FOpenvStorage%2Fconfig%2Farakoon_cacc.ini --lock-file /opt/OpenvStorage/run/storagedriver_vmstor.lock --logrotation --mountpoint /mnt/vmstor --logsink console: -o big_writes -o sync_read -o allow_other -o use_ino -o default_permissions -o uid=1001 -o gid=1001 -o umask=0002
libust[40377/40377]: Warning: HOME environment variable not set. Disabling LTTng-UST per-user tracing. (in setup_local_apps() at lttng-ust-comm.c:305)
2016-10-14 21:30:31 219052 +0200 - stor-08.be-g8-4 - 40377/0x00007f367e554940 - volumedriverfs/volumedriver_fs - 0000000000000000 - notice - print_version_data: version: 6.2.0
version revision: dd285ef05452cf6862dd4cc689b1a603c32467a9
branch: dev
md5 support: no
revision: e626fea2c2883e63142b17d43f69ed8b3f0540c4
build time: Thu Oct 13 17:28:27 UTC 2016
```

**Comment by wimpers** [comment]
@redlicha can you give some background? Is this urgent what does it break? SRP or not?

**Comment by redlicha** [comment]
@wimpers:

From the `write(2)` manpage:
> EPIPE  fd  is  connected  to  a pipe or socket whose reading end is closed.  When this happens the  writing process will also receive a SIGPIPE signal.  (Thus, the write return value is seen only if the         program catches, blocks or ignores this signal.)

So some pipe or socket was closed and voldrv was trying to write to it. The exact source is unclear, but it's a bug in any case since the intention has always been that in that case we want to handle the error returned by `write` instead of being notified asynchronously with a signal. We've not seen it more often so far since the FUSE main loop blocks the signal but there is a window during startup before the signal is blocked. If the signal arrives during that window, it will take down the process.

The fix should be pretty simple (and is in fact already in a branch, see the above commit). I propose to label it SRP but not to give it high urgency (if that makes any sense?).

**Comment by wimpers** [comment]
Closed by PM.
