### ISSUE TITLE
libovsvolumedriver versioning

### ISSUE THREAD

**Issue by redlicha** [openvstorage/volumedriver#156]
Currently the .so version is 0.0.0 . Make sure that interface changes are reflected there in the future. Consider the package names as well.

**Comment by cnanakos** [comment]
Libtool's -version-info flag during link mode can be used. The flag accepts an argument of the form ‘current[:revision[:age]]’. More info can be found on libtool's relevant page.

https://www.gnu.org/software/libtool/manual/html_node/Updating-version-info.html
