### ISSUE TITLE
Prevent failover if DTL is degraded / not sync

### ISSUE THREAD

**Issue by redlicha** [openvstorage/volumedriver#158]

**Comment by wimpers** [comment]
Do not that there should always be a force command possible. We don't want to be in deadlock where we can't move the volume as the DTL was degraded and the host owning the volume was down.

**Comment by redlicha** [comment]
The `migrate` API call offers that.

**Comment by khenderick** [comment]
@wimpers, if this "force" should be exposed though e.g. the API, please create a ticket on the framework repo for that. At this moment, we pass this parameter as ```False```.

**Comment by wimpers** [comment]
Please implement an error.

**Comment by wimpers** [comment]
Closed by PM.
