### ISSUE TITLE
Prevent HA events from occupying all WQ threads

### ISSUE THREAD

**Issue by redlicha** [openvstorage/volumedriver#160]
Idea: trigger stealing with `open` request opposed to actual I/O.

**Comment by wimpers** [comment]
@redlicha isn't this one solved in  6.3.4 ? See https://github.com/openvstorage/volumedriver/releases/tag/6.3.4

**Comment by redlicha** [comment]
@wimpers : the changeset in 6.3.4 *alleviates* the issue by having only one (instead of multiple) workqueue threads trigger the failover with a fairly simple change. It still leaves the issue that multiple failovers could occupy all WQ threads, which is addressed in another changeset by @cnanakos that will be included in the next release ( 07ae580bdb8ff4e2ce2a9dc65179f458904b4612 ).

**Comment by redlicha** [comment]
@khenderick as a FYI: the fix (released with https://github.com/openvstorage/volumedriver/releases/tag/6.4.0 ) introduces a new configurable to control the max number of threads for the control plane:
   network_interface/network_workqueue_ctrl_max_threads
   ** default value: 128
   ** not dynamically reconfigurable
.
