### ISSUE TITLE
Expose list_clones call

### ISSUE THREAD

**Issue by kvanhijf** [openvstorage/volumedriver#164]
Would it be possible to introduce a call like "list_clones" or add additional information in volume_info about the clones of a volume (not necessary for recursive information)

This would come in very handy for the framework team

**Comment by redlicha** [comment]
Yes, it's possible - this information is kept in the ObjectRegistry. Exposing it via interfaces `ObjectRegistryClient` / `ObjectRegistration` types would make most sense.

**Comment by wimpers** [comment]
@kvanhijf  very handy for what exactly?

**Comment by kvanhijf** [comment]
Now we keep this information in our model, which doesn't make sense.
We use this information to allow certain actions on disks such as deletion, convert to template, ...

**Comment by wimpers** [comment]
@redlicha  wasn't this feature delivered as part if the sub snapshot cloning? Hence can this one be closed?

**Comment by redlicha** [comment]
Yes, that's right.
