### ISSUE TITLE
I/O request getting queued to old connection

### ISSUE THREAD

**Issue by redlicha** [openvstorage/volumedriver#169]
* I/O thread I: get `ContextPtr` C
* HA thread H: while holding mutex M: detect connection loss, create new `ContextPtr` C' and resend all inflight tasks using C'
* I: acquire M, submit new I/O with C 
.

=> I obtaining C should happen under M as well

**Comment by redlicha** [comment]
Not observed anymore in 200 iterations of `NetworkServerTest.ha_stress` whereas previously it was observed with that test.

**Comment by kinvaris** [comment]
@redlicha any way to easily test this by QA?

**Comment by redlicha** [comment]
@kinvaris no, but the issue not being reproducible anymore in the voldrv tests gives enough confidence. Closing it (as also discussed with @pploegaert ).
