### ISSUE TITLE
NetworkXioClient hang on shutdown

### ISSUE THREAD

**Issue by cnanakos** [openvstorage/volumedriver#171]
Thread 6 (Thread 0x7fa649eff700 (LWP 2562)):
#0  0x00007fa6885879dd in pthread_join (threadid=140352882448128, thread_return=0x0) at pthread_join.c:90
#1  0x00007fa68725db97 in std::thread::join() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x00007fa688854711 in libovsvolumedriver::NetworkXioClient::shutdown (this=0x122f400)
    at /opt/vmachines/jenkins_work/workspace/volumedriver-no-dedup-release-ubuntu-16.04/volumedriver-core/src/filesystem/c-api/NetworkXioClient.cpp:284
#3  0x00007fa68885514e in libovsvolumedriver::NetworkXioClient::~NetworkXioClient (this=0x122f400, __in_chrg=<optimized out>)
    at /opt/vmachines/jenkins_work/workspace/volumedriver-no-dedup-release-ubuntu-16.04/volumedriver-core/src/filesystem/c-api/NetworkXioClient.cpp:296
#4  0x00007fa68885d831 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x122f3f0) at /usr/include/c++/5/bits/shared_ptr_base.h:150
#5  std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count (this=<optimized out>, __in_chrg=<optimized out>) at /usr/include/c++/5/bits/shared_ptr_base.h:659
#6  std::__shared_ptr<libovsvolumedriver::NetworkXioClient, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr (this=<optimized out>, __in_chrg=<optimized out>) at /usr/include/c++/5/bits/shared_ptr_base.h:925
#7  std::__shared_ptr<libovsvolumedriver::NetworkXioClient, (__gnu_cxx::_Lock_policy)2>::reset (this=<optimized out>) at /usr/include/c++/5/bits/shared_ptr_base.h:1022
---Type <return> to continue, or q <return> to quit---
#8  libovsvolumedriver::NetworkXioContext::close_volume (this=<optimized out>)
    at /opt/vmachines/jenkins_work/workspace/volumedriver-no-dedup-release-ubuntu-16.04/volumedriver-core/src/filesystem/c-api/NetworkXioContext.cpp:155
#9  0x00007fa68884c148 in libovsvolumedriver::NetworkHAContext::close_volume (this=<optimized out>)
    at /opt/vmachines/jenkins_work/workspace/volumedriver-no-dedup-release-ubuntu-16.04/volumedriver-core/src/filesystem/c-api/NetworkHAContext.cpp:432
#10 0x00007fa68887b168 in ovs_ctx_destroy (ctx=0x122dcf0) at /opt/vmachines/jenkins_work/workspace/volumedriver-no-dedup-release-ubuntu-16.04/volumedriver-core/src/filesystem/c-api/libovsvolumedriver.cpp:261
#11 0x0000000000475c12 in _fio_ovs_destroy_ctx (ovs_data_=0x122a010) at engines/openvstorage.c:149
#12 fio_ovs_cleanup (td=0x7fa67433b000) at engines/openvstorage.c:346
#13 0x000000000041c006 in close_ioengine (td=td@entry=0x7fa67433b000) at ioengines.c:184
#14 0x000000000045d148 in thread_main (data=<optimized out>) at backend.c:1775
#15 0x00007fa68858670a in start_thread (arg=0x7fa649eff700) at pthread_create.c:333
#16 0x00007fa6880b882d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 5 (Thread 0x7fa673b39700 (LWP 2551)):
#0  0x00007fa6880b8e23 in epoll_wait () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007fa685670f53 in ?? () from /usr/lib/x86_64-linux-gnu/libxio.so.0
#2  0x00007fa685673735 in xio_context_run_loop () from /usr/lib/x86_64-linux-gnu/libxio.so.0
#3  0x00007fa688854cc2 in libovsvolumedriver::NetworkXioClient::xio_run_loop_worker (this=0x122f400)
    at /opt/vmachines/jenkins_work/workspace/volumedriver-no-dedup-release-ubuntu-16.04/volumedriver-core/src/filesystem/c-api/NetworkXioClient.cpp:340
#4  0x00007fa688858ec8 in libovsvolumedriver::NetworkXioClient::run (this=0x122f400, promise=...)
    at /opt/vmachines/jenkins_work/workspace/volumedriver-no-dedup-release-ubuntu-16.04/volumedriver-core/src/filesystem/c-api/NetworkXioClient.cpp:273
#5  0x00007fa688859816 in libovsvolumedriver::NetworkXioClient::<lambda()>::operator() (__closure=<optimized out>)
    at /opt/vmachines/jenkins_work/workspace/volumedriver-no-dedup-release-ubuntu-16.04/volumedriver-core/src/filesystem/c-api/NetworkXioClient.cpp:155
#6  std::_Bind_simple<libovsvolumedriver::NetworkXioClient::NetworkXioClient(const string&, uint64_t, libovsvolumedriver::NetworkHAContext&, bool)::<lambda()>()>::_M_invoke<> (this=<optimized out>)
    at /usr/include/c++/5/functional:1531
#7  std::_Bind_simple<libovsvolumedriver::NetworkXioClient::NetworkXioClient(const string&, uint64_t, libovsvolumedriver::NetworkHAContext&, bool)::<lambda()>()>::operator() (this=<optimized out>)
    at /usr/include/c++/5/functional:1520
#8  std::thread::_Impl<std::_Bind_simple<libovsvolumedriver::NetworkXioClient::NetworkXioClient(const string&, uint64_t, libovsvolumedriver::NetworkHAContext&, bool)::<lambda()>()> >::_M_run(void) (this=0x122d610)
    at /usr/include/c++/5/thread:115
#9  0x00007fa68725dc80 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#10 0x00007fa68858670a in start_thread (arg=0x7fa673b39700) at pthread_create.c:333
#11 0x00007fa6880b882d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

**Comment by redlicha** [comment]
Fixed in 6.3.4.

**Comment by pploegaert** [comment]
@dejonghb: can you pls validate this one in your fio test setup? thx

**Comment by dejonghb** [comment]
System now spinning happily, so issue is fixed.
