### ISSUE TITLE
Failure to claim a namespace after creation leaks the namespace

### ISSUE THREAD

**Issue by redlicha** [openvstorage/volumedriver#176]
```
Nov 13 23:21:42 ftcmp02 volumedriver_fs.sh[11730]: 2016-11-13 23:21:42 649439 +0100 - ftcmp02 - 11730/0x00007f0ecf7fe700 - volumedriverfs/BackendConnectionInterfaceLogger - 00000000007c2f59 - error - ~Logger: Exiting write_tag for 0041b478-f26a-4b5f-921c-29437944cfea owner_tag with exception
Nov 13 23:21:42 ftcmp02 volumedriver_fs.sh[11730]: 2016-11-13 23:21:42 649467 +0100 - ftcmp02 - 11730/0x00007f0ecf7fe700 - volumedriverfs/BackendConnectionInterfaceLogger - 00000000007c2f5a - error - ~Logger: Exiting write_tag for 0041b478-f26a-4b5f-921c-29437944cfea
Nov 13 23:21:42 ftcmp02 volumedriver_fs.sh[11730]: 2016-11-13 23:21:42 649617 +0100 - ftcmp02 - 11730/0x00007f0ecf7fe700 - volumedriverfs/VolManager - 00000000007c2f5d - notice - New Volume, VolumeId: 0041b478-f26a-4b5f-921c-29437944cfea, Namespace: 0041b478-f26a-4b5f-921c-29437944cfea, Size: 0, CreateNamespace: CreateNamespace::T, EXCEPTION
Nov 13 23:21:42 ftcmp02 volumedriver_fs.sh[11730]: 2016-11-13 23:21:42 649644 +0100 - ftcmp02 - 11730/0x00007f0ecf7fe700 - volumedriverfs/VFSLocalNode - 00000000007c2f5e - error - create_volume_: Failed to create volume 0041b478-f26a-4b5f-921c-29437944cfea: invalid inputstream
Nov 13 23:21:42 ftcmp02 volumedriver_fs.sh[11730]: 2016-11-13 23:21:42 649659 +0100 - ftcmp02 - 11730/0x00007f0ecf7fe700 - volumedriverfs/ObjectRegistry - 00000000007c2f5f - info - unregister: 7ee9f357-bf77-4b11-85be-1e1b08184819/vp1TkO7BtROEN7zRh2J: unregistering 0041b478-f26a-4b5f-921c-29437944cfea
Nov 13 23:21:42 ftcmp02 volumedriver_fs.sh[11730]: 2016-11-13 23:21:42 667179 +0100 - ftcmp02 - 11730/0x00007f0ecf7fe700 - volumedriverfs/VFSLocalNode - 00000000007c2f61 - error - create_volume_: 0041b478-f26a-4b5f-921c-29437944cfea: failed to create volume: invalid inputstream
```

**Comment by pploegaert** [comment]
@dejonghb: pls validate in fio test setup - thx

**Comment by dejonghb** [comment]
Present state (where leaked namespaces were deleted by Arne, but were alba still had an issue) still appears to have too much namespaces which seems like some leak. 
```
# alba list-namespaces --config arakoon://config/ovs/arakoon/be1-abm/config?ini=%2Fopt%2FOpenvStorage%2Fconfig%2Farakoon_cacc.ini | grep state |wc -l
668
```
with 2x30 vdisks.
When vdisks are removed the amount goes down, and when recreating 2 more vdisks afterwards, indeed 2 extra namespaces are found.
Guess is the removal of namespaces was tried when alba had some issue and then the namespace was still leaked? (removal failed but is never retried?)

**Comment by redlicha** [comment]
FWIW, I've not deleted any namespaces manually, so could these still be a leftover from earlier tests where the leak was still present? Other than that your other hypothesis holds - if the namespace removal fails it is not retried. Similar as for #71 , a garbage collector would be desirable to take care of this.

**Comment by dejonghb** [comment]
These extra namespaces most probably are a leftover from when things were still going wrong. Now that the system is happy, nothing is being leaked. Untill there's some garbage collector there's still the potential of leaked namespaces if part of the system is not happy/healthy resulting in failure with removing the namespace. Now the removal is tried, so I'm closing this ticket (#71 mentions the garbage collection as the proper fix) -- feel free to re-open if it's needed as an extra reminder of why garbage collection is required.
