### ISSUE TITLE
Lowering the number of metadata cache pages requires volumedriver restart to free the memory

### ISSUE THREAD

**Issue by saelbrec** [openvstorage/volumedriver#201]
Lowering the metadata page capacity for a certain volume does not immediately free up the memory used. It apparently requires a volumedriver restart. Did not test a single volume restart, maybe that suffices as well?

**Comment by redlicha** [comment]
A volume restart should indeed take care of this

**Comment by pploegaert** [comment]
Validation continued in:
https://github.com/openvstorage/integrationtests/issues/437
