### ISSUE TITLE
Multiple proxies per volumedriver

### ISSUE THREAD

**Issue by wimpers** [openvstorage/volumedriver#206]
In https://github.com/openvstorage/framework/issues/1274 the framework will set up 8 proxies per voldrv. This ticket is to make sure the voldrv can use these 8 proxies. Each namespace should go to 1 specific proxy of the 8 proxies.

**Comment by redlicha** [comment]
@khenderick: volumedriver currently has a(n unused by OVS) `MULTI` backend config (previous use case: specify fallback paths that are used in case of connection errors, only supports `LocalBackend` these days). The idea is to reanimate this, adding support for `ALBA` backends. Example (with `LocalBackend`):

```
{
    "backend_connection_manager": {
        "backend_type": "MULTI",
        "0": {
            "backend_type": "LOCAL",
            "local_connection_path": "/tmp/multi_dir_0"
        },
        "1": {
            "backend_type": "LOCAL",
            "local_connection_path": "/tmp/multi_dir_1"
        },
        "2": {
            "backend_type": "LOCAL",
            "local_connection_path": "/tmp/multi_dir_2"
        }
    }
}
```

**Comment by khenderick** [comment]
@redlicha, will there be a particular order in the different backends (```0```, ```1````, ...)
