### ISSUE TITLE
Provide means to startup volumedriver without automatically starting all volumes and manage/remove volumes

### ISSUE THREAD

**Issue by pploegaert** [openvstorage/volumedriver#207]
Related to: 
http://tickets.openvstorage.com/browse/OVSSUP-140
http://tickets.openvstorage.com/browse/OVSSUP-148

In this case we'd have to remove certain volumes as the system was overprovisioned x times
This caused the system to grind down to an almost halted state so it would take us days to cleanup most of the volumes.  Which we were allowed to do.
In order to avoid to revert to a complete reinstall this feature might prove to very useful for support reasons.

**Comment by wimpers** [comment]
@redlicha can you provide a ballpark figure for time to implement? Is this a big change?

**Comment by redlicha** [comment]
The simplest approach would be a command line option (`--dont-start-volumes` or something akin to that), which should not be much effort (< 1h). Individual volumes can then be restarted with the Python API. There is however no simple way to remove a volume that is not running. This entails:
* removing the directory entry
* removing the object registration
* removing local artefacts (SCO cache contents, TLogs)
* removing MDS slaves
* removing the backend namespace
.
