### ISSUE TITLE
Catch error in case there is no RDMA device and show meaningful error

### ISSUE THREAD

**Issue by wimpers** [openvstorage/volumedriver#209]
```
2016-12-17 08:13:18 931793 -0800 - ubuntu-16 - 24199/0x00007fcd2ef50740 - dtl_server//usr/bin/failovercache - 0000000000000002 - info - run: starting, server path:  "/mnt/hdd4/pstorage_write_dtl_1", address to bind to:  125.212.218.15, port: 26217, transport type: RSocket, busy-loop usecs: 0
[...]
dtl_server//usr/bin/failovercache - 0000000000000005 - fatal - operator(): caught exception: socket  No such device (19)
```

DTL is configured to use RSocket, but it looks like there's no RDMA device / the wrong one is specified.

**Comment by wimpers** [comment]
This line gives away there is no RDMA device

`2016-12-17 08:13:18 932460 -0800 - ubuntu-16 - 24199/0x00007fcd2ef50740 - dtl_server//usr/bin/failovercache - 0000000000000005 - fatal - operator(): caught exception: socket  No such device (19)`

**Comment by wimpers** [comment]
from @redlicha 

> What would be possible without much effort is rewording the exception message from "socket No such device (19)" to something a bit more descriptive, i.e. "Failed to create socket: No such device (19)". But it's again an error coming from a library / the OS (ENODEV), so giving a good context sensitive translation is tricky.

**Comment by wimpers** [comment]
Framework no longer allows to select RDMA when no RDMA device is there. @khenderick  right?

**Comment by khenderick** [comment]
@wimpers, indeed.
