### ISSUE TITLE
Local volume restart taking very long due to DTL connect timeout not being used

### ISSUE THREAD

**Issue by redlicha** [openvstorage/volumedriver#213]
Scenario:
* write to volume, wait for all TLogs / SCOs that are in flight to hit the backend, leave unfinished local TLogs
* shut down volumedriver
* remove disposable SCOs from local cache
* on restart, the following is observed:
```
 Dec 20 22:08:27 stor-01.be-g8-4 volumedriver_fs.sh[6765]: 2016-12-20 22:08:27 132597 +0100 - stor-01.be-g8-4 - 6765/0x00007fe87684b900 - volumedriverfs/ZCOVetcher - 0000000000001365 - info - getSCO: With FailOverCache, trying to get SCO 00_00000067_00 from the FOC or the backend
[...]
Dec 20 22:13:23 stor-01.be-g8-4 volumedriver_fs.sh[6765]: 2016-12-20 22:13:23 064920 +0100 - stor-01.be-g8-4 - 6765/0x00007fe87684b900 - volumedriverfs/Socket - 0000000000001693 - error - connect: error connecting to 10.109.3.44:26202 - connect timeout
```

The `dtl_connect_timeout` was however configured to 1000 milliseconds, and the DTL was also running:
```
 u'dtl_busy_loop_usecs': u'0',
 u'dtl_check_interval_in_seconds': u'300',
 u'dtl_connect_timeout_ms': u'1000',
 u'dtl_queue_depth': u'1024',
 u'dtl_request_timeout_ms': u'60000',
 u'dtl_throttle_usecs': u'4000',
 u'dtl_write_trigger': u'8',
 ```

**Comment by redlicha** [comment]
NB: env is RDMA capable. Since the DTL code probes for RSocket first it might be related to that?

**Comment by redlicha** [comment]
=> dtl_connect_timeout is not used in this code path, instead the default value is passed in.
(NB: the env where this was observed is RDMA capable)

**Comment by redlicha** [comment]
Looking at the code, a DTL fetcher (that connects to the DTL) is instantiated "just in case", i.e. afterwards the SCO cache is consulted and if the SCO is found there (which is the more likely case), the DTL will not be used. So as a future improvement connecting to the DTL could be delayed?

**Comment by wimpers** [comment]
Closed by PM.
