### ISSUE TITLE
Work around buggy alba proxy in case multiple proxies are configured

### ISSUE THREAD

**Issue by domsj** [openvstorage/volumedriver#215]
In case of bugs in the alba proxy (such as https://github.com/openvstorage/alba/issues/449 & https://github.com/openvstorage/alba/issues/461) it would be nice if the volumedriver could fall back to one of the other alba proxies it knows about.
(This gives the monitoring some time to pick up on the buggy proxy and e.g. restart it)

**Comment by redlicha** [comment]
related to #206

**Comment by redlicha** [comment]
Currently there are connection pools per proxy, with namespaces being mapped to specific pools. In case of certain errors (for starters: failure to create a new client - something else?), a pool could be blacklisted and any user be redirected to the pool that is next in line that is not blacklisted. The blacklisting is removed again after a certain time.
+/- 1d.

**Comment by wimpers** [comment]
Note to self:

each request to the backend works like this
* get connection from pool (if empty, create a new connection)
* perform request
* release connection back to pool if ok, otherwise try again, this time forcing a new connection from the pool (on relevant errors)

**Comment by wimpers** [comment]
After discussion with stakeholders, decided to be added to RC4.

**Comment by pploegaert** [comment]
Add to non-happy path test suite:
https://github.com/openvstorage/integrationtests/issues/449

**Comment by redlicha** [comment]
Related: #337

**Comment by wimpers** [comment]
Closed by PM.
