### ISSUE TITLE
Integrate Alba client lib with ASD client functionality

### ISSUE THREAD

**Issue by redlicha** [openvstorage/volumedriver#219]
https://github.com/openvstorage/alba/issues/545

**Comment by redlicha** [comment]
@khenderick, FYI : a new configurable `backend_connection_manager/alba_connection_asd_connection_pool_capacity` was introduced: `size_t`, default value 5, not dynamically reconfigurable.

**Comment by kinvaris** [comment]
FAILED: regression test showed this result
https://github.com/openvstorage/alba/issues/560

**Comment by redlicha** [comment]
The failed test is not related to the voldrv integration.

**Comment by wimpers** [comment]
Putting it to state_verification  see last comment of Arne

**Comment by JeffreyDevloo** [comment]
This update has been a part of our performance-test suite and has shown its results.
Closing.
