### ISSUE TITLE
Make sure that the quorum flag is passed using etcd

### ISSUE THREAD

**Issue by khenderick** [openvstorage/volumedriver#25]
Make sure that the quorum flag is passed using etcd

**Comment by wimpers** [comment]
@redlicha what is the status of this ticket? @saelbrec believes it was already fixed.

**Comment by redlicha** [comment]
PR still needs review: https://github.com/openvstorage/volumedriver/pull/27

**Comment by redlicha** [comment]
Fix was merged into dev branch.

**Comment by redlicha** [comment]
New dev packages including the fix were uploaded to unstable.
