### ISSUE TITLE
Directories can be renamed

### ISSUE THREAD

**Issue by khenderick** [openvstorage/volumedriver#252]
While volumes cannot be renamed, directories can. This results in the model being out-of-sync with reality. We would either need an event that informs us about the directory rename, or block directory renames at all.

If we decide that renaming directories (or volumes for that matter) need to be possible and an event is added, it would also be interesting to expose a call on the volumedriver API that can find the path for a given volume_id.

**Comment by wimpers** [comment]
@redlicha will this be part of RC4? 

@khenderick any chance we can integrate it for RC4? Please create an integration ticket on the framework.

**Comment by khenderick** [comment]
@wimpers, this _is_ the integration ticket. After the integration of this new API it will be possible to get the devicename back in sync after a manual intervention from Ops, as we don't do this automatically (as we would need the new event for that)

**Comment by redlicha** [comment]
Looking at the code, `FileRenameEvent`s should also be emitted if the event rules match `rename`s of directories.

#259 will be part of RC4 (via #262).

**Comment by khenderick** [comment]
@redlicha, do you mean that I should reintroduce the `FileRenameEvent` with a regex on `*.raw` so we also get "renames" of the directories containing the raw files?

**Comment by redlicha** [comment]
No, it doesn't work that way - the children are not matched, only `from` and `to` of the rename operation (volumes are children of these in case of directories):
https://github.com/openvstorage/volumedriver/blob/dev/src/filesystem/FileSystem.cpp#L643-L658

**Comment by wimpers** [comment]
@redlicha  do I get it correct that this one can be closed as the voldrv team has nothing to do for this one?

**Comment by redlicha** [comment]
@wimpers: if the approach discussed above works for @khenderick it can be closed.

**Comment by khenderick** [comment]
@wimpers, it does work and is integrated.
