### ISSUE TITLE
Expose API to check whether a volume is being restarted

### ISSUE THREAD

**Issue by kvanhijf** [openvstorage/volumedriver#253]
The framework has implemented a call to restart a volume, but since its unclear how long this restart can take, it might be nice to be able to block other API calls for that volume while the restart is ongoing. therefore we would need this information
Eg: Volume is being restarted, so it might not be wise to snapshot, clone, convert to template, delete, move, restart again, ...

**Comment by redlicha** [comment]
There is a "VolumeOverview" mgmt call per voldrv instance that lists all volumes belonging to that instance and their state ("Active" or "Restarting"). Exposing that directly in the Python API can be done with relatively little effort - +/- 2 h.

**Comment by redlicha** [comment]
@kvanhijf : PR #260 introduces a new `VolumeRestartInProgress` exception (for `info_volume`, `list_snapshots` etc), originally to address #258 .

**Comment by redlicha** [comment]
Part of 6.10.0

**Comment by redlicha** [comment]
@khenderick , can this one be closed?

**Comment by khenderick** [comment]
It's currently implemented and in use.

**Comment by redlicha** [comment]
Manually tested, closing after discussion with @khenderick"
