### ISSUE TITLE
Cannot create vpool on ubuntu 16.04 with fargo version

### ISSUE THREAD

**Issue by hoanhdo** [openvstorage/volumedriver#254]
I cannot create vpool. This is my log

> Feb  2 15:06:39 openvstorage volumedriver_fs.sh[25057]: 2017-02-02 15:06:39 854769 +0700 - openvstorage - 25057/0x00007fd93b578900 - volumedriverfs/volumedriver_fs - 000000
000000012e - notice - at_exit: Time spent executing user instructions (seconds): 0.264000
Feb  2 15:06:39 openvstorage volumedriver_fs.sh[25057]: Time spent in operating system code (seconds): 0.24000
Feb  2 15:06:39 openvstorage volumedriver_fs.sh[25057]: The maximum resident set size used, in kilobytes. 38608
Feb  2 15:06:39 openvstorage volumedriver_fs.sh[25057]: The number of page faults which were serviced without requiring any I/O: 1907
Feb  2 15:06:39 openvstorage volumedriver_fs.sh[25057]: The number of page faults which were serviced by doing I/O: 0
Feb  2 15:06:39 openvstorage volumedriver_fs.sh[25057]: The number of times PROCESSES was swapped entirely out of main memory: 0
Feb  2 15:06:39 openvstorage volumedriver_fs.sh[25057]: The number of times the file system had to read from the disk: 8
Feb  2 15:06:39 openvstorage volumedriver_fs.sh[25057]: The number of times the file system had to write to the disk: 48
Feb  2 15:06:39 openvstorage volumedriver_fs.sh[25057]: The number of signals received: 0
Feb  2 15:06:39 openvstorage volumedriver_fs.sh[25057]: The number of times PROCESSES voluntarily invoked a context switch: 159
Feb  2 15:06:39 openvstorage volumedriver_fs.sh[25057]: The number of times an involuntary context switch took place: 282
Feb  2 15:06:39 openvstorage systemd[1]: ovs-volumedriver_vpooldemo.service: Main process exited, code=exited, status=1/FAILURE
Feb  2 15:06:39 openvstorage systemd[1]: ovs-volumedriver_vpooldemo.service: Unit entered failed state.
Feb  2 15:06:39 openvstorage systemd[1]: ovs-volumedriver_vpooldemo.service: Failed with result 'exit-code'.
Feb  2 15:06:39 openvstorage arakoon[23515]: 2017-02-02 15:06:39 975723 +0700 - openvstorage - 23515/0 - arakoon - 67 - info - 3pexFl75D8h1vLju is master
Feb  2 15:06:40 openvstorage celery[20764]: 2017-02-02 15:06:40 05100 +0700 - openvstorage - 20764/139652309022464 - celery/celery.worker.job - 106 - ERROR - Task ovs.storagerouter.add_vpool[05964ea8-9b11-4feb-83e3-8c08d560f48b] raised unexpected: RuntimeError('StorageDriver service failed to start (service not running)',)
Feb  2 15:06:40 openvstorage celery[20764]: Traceback (most recent call last):
Feb  2 15:06:40 openvstorage celery[20764]:   File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
Feb  2 15:06:40 openvstorage celery[20764]:     R = retval = fun(*args, **kwargs)
Feb  2 15:06:40 openvstorage celery[20764]:   File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
Feb  2 15:06:40 openvstorage celery[20764]:     return self.run(*args, **kwargs)
Feb  2 15:06:40 openvstorage celery[20764]:   File "/opt/OpenvStorage/ovs/lib/storagerouter.py", line 832, in add_vpool
Feb  2 15:06:40 openvstorage celery[20764]:     raise RuntimeError('StorageDriver service failed to start (service not running)')
Feb  2 15:06:40 openvstorage celery[20764]: RuntimeError: StorageDriver service failed to start (service not running)
Feb  2 15:06:40 openvstorage gunicorn[20707]: 2017-02-02 09:06:40 37500 +0100 - openvstorage - 20747/140026023139920 - log/api - 98 - INFO - [messaging.wait] - e1fcadcf-0177-411c-ad2d-5ebb750dce0b - [] - {"pk": "5012341184"} - {"cookies": {"csrftoken": "PzYGQi46V57lzUTxO4LK1wTwLNsQ3OdZ", "sessionid": "h093brhkritofe4ppr0p3m8x80p0ijf6"}, "meta": {"HTTP_AUTHORIZATION": "Bearer XGnxORNr_[5kBup?}65}AGr|Q![IhW7iyy//4QHyaf4-IHBldwS5b7Tj!fh}hzX@", "wsgi.multiprocess": "True", "HTTP_COOKIE": "csrftoken=PzYGQi46V57lzUTxO4LK1wTwLNsQ3OdZ; sessionid=h093brhkritofe4ppr0p3m8x80p0ijf6", "HTTP_X_FORWARDED_SSL": "on", "SERVER_SOFTWARE": "gunicorn/19.4.5", "SCRIPT_NAME": "/api", "REQUEST_METHOD": "GET", "PATH_INFO": "/messages/5012341184/wait/", "SERVER_PROTOCOL": "HTTP/1.0", "QUERY_STRING": "message_id=17&timestamp=1486022802413", "HTTP_X_REAL_IP": "172.16.86.1", "HTTP_USER_AGENT": "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0", "HTTP_CONNECTION": "close", "HTTP_REFERER": "https://172.16.86.132/", "SERVER_NAME": "127.0.0.1", "REMOTE_PORT": "43624", "wsgi.url_scheme": "https", "SERVER_PORT": "8002", "HTTP_X_SCHEME": "https", "HTTP_X_REQUESTED_WITH": "XMLHttpRequest", "wsgi.input": "<gunicorn.http.body.Body object at 0x7f5a59520910>", "HTTP_HOST": "172.16.86.132", "wsgi.multithread": "True", "HTTP_ACCEPT": "application/json; version=*", "wsgi.version": "(1, 0)", "RAW_URI": "/messages/5012341184/wait/?message_id=17&timestamp=1486022802413", "wsgi.run_once": "False", "wsgi.errors": "<gunicorn.http.wsgi.WSGIErrorsWrapper object at 0x7f5a59520c90>", "REMOTE_ADDR": "127.0.0.1", "HTTP_ACCEPT_LANGUAGE": "en-US,en;q=0.5", "gunicorn.socket": "<socket fileno=13 sock=127.0.0.1:8002 peer=127.0.0.1:43624>", "CONTENT_TYPE": "application/json", "wsgi.file_wrapper": "<class 'gunicorn.http.wsgi.FileWrapper'>", "CSRF_COOKIE": "PzYGQi46V57lzUTxO4LK1wTwLNsQ3OdZ", "HTTP_ACCEPT_ENCODING": "gzip, deflate"}, "request": {"timestamp": "1486022802413", "message_id": "17"}}

**Comment by kvanhijf** [comment]
Hi,

What do you see in 'journalctl -u ovs-volumedriver_vpooldemo.service'

**Comment by hoanhdo** [comment]
@kvanhijf 
this is my log.

[log_vpool.txt](https://github.com/openvstorage/volumedriver/files/747218/log_vpool.txt)

**Comment by kvanhijf** [comment]
This seems to be the problem to me:

[ERROR] - failed to load rdma transport layer.
Feb 02 15:44:44 openvstorage volumedriver_fs.sh[5456]:
[2017/02/02-15:44:44.18952] xio_nexus.c:1864             [ERROR] - validate
that your system support rdma and the accelio's rdma module is loaded
Feb 02 15:44:44 openvstorage volumedriver_fs.sh[5456]:
[2017/02/02-15:44:44.18957] xio_server.c:357             [ERROR] - failed
to create connection
Feb 02 15:44:44 openvstorage volumedriver_fs.sh[5456]: 2017-02-02 15:44:44
018965 +0700 - openvstorage - 5456/0x00007f27167fc700 -
volumedriverfs/NetworkXioServer - 0000000000000102 - fatal - run: failed to
bind XIO server to 'rdma://172.16.86.132:26203'


RDMA is not configured (properly) i guess

**Comment by hoanhdo** [comment]
@kvanhijf 
Yes. I config wrong RDMA.
Thanks.
