### ISSUE TITLE
create backend error

### ISSUE THREAD

**Issue by hoanhdo** [openvstorage/volumedriver#265]
Hi all.
I install openvstorage in GeoScale model, version fargo

I create localbackend error.
Unknown --to-json parameter in command
/usr/bin/alba' 'update-abm-client-config' '--to-json' '--config=arakoon://config/ovs/arakoon/localbackend5-abm/config?ini=%2Fopt%2FOpenvStorage%2Fconfig%2Farakoon_cacc.ini

> Feb 10 15:56:00 ovs-performance celery[1954]: 2017-02-10 15:56:00 91500 +0700 - ovs-performance - 1998/140085523240704 - lib/alba - 15 - INFO - Creating arakoon cluster: localbackend5-abm
Feb 10 15:56:01 ovs-performance celery[1954]: 2017-02-10 15:56:01 13800 +0700 - ovs-performance - 1998/140085523240704 - extensions/arakoon_installer - 16 - DEBUG - Creating cluster localbackend5-abm on 172.16.86.136
Feb 10 15:56:01 ovs-performance celery[1954]: 2017-02-10 15:56:01 60500 +0700 - ovs-performance - 1998/140085523240704 - extensions/arakoon_installer - 18 - DEBUG - Cleaning old Arakoon - Checking directory /mnt/hdd1/arakoon/localbackend5-abm/db
Feb 10 15:56:01 ovs-performance celery[1954]: 2017-02-10 15:56:01 84800 +0700 - ovs-performance - 1998/140085523240704 - extensions/arakoon_installer - 19 - DEBUG - Cleaning old Arakoon - Checking directory /mnt/hdd1/arakoon/localbackend5-abm/tlogs
Feb 10 15:56:02 ovs-performance celery[1954]: 2017-02-10 15:56:02 05800 +0700 - ovs-performance - 1998/140085523240704 - extensions/arakoon_installer - 21 - DEBUG - Deploying cluster localbackend5-abm
Feb 10 15:56:02 ovs-performance celery[1954]: 2017-02-10 15:56:02 05800 +0700 - ovs-performance - 1998/140085523240704 - extensions/arakoon_installer - 22 - DEBUG -   Deploying cluster localbackend5-abm on 172.16.86.136
Feb 10 15:56:03 ovs-performance celery[1954]: 2017-02-10 15:56:03 59400 +0700 - ovs-performance - 1998/140085523240704 - extensions/arakoon_installer - 23 - DEBUG -   Deploying cluster localbackend5-abm on 172.16.86.136 completed
Feb 10 15:56:03 ovs-performance celery[1954]: 2017-02-10 15:56:03 71000 +0700 - ovs-performance - 1998/140085523240704 - extensions/arakoon_installer - 26 - DEBUG - Creating cluster localbackend5-abm on 172.16.86.136 completed
Feb 10 15:56:04 ovs-performance celery[1954]: 2017-02-10 15:56:04 20100 +0700 - ovs-performance - 1998/140085523240704 - extensions/arakoon_installer - 27 - DEBUG - Restart sequence (add) for localbackend5-abm
Feb 10 15:56:05 ovs-performance celery[1954]: 2017-02-10 15:56:05 86100 +0700 - ovs-performance - 1998/140085523240704 - extensions/arakoon_installer - 30 - DEBUG - Waiting for cluster localbackend5-abm
Feb 10 15:56:06 ovs-performance celery[1954]: 2017-02-10 15:56:06 07500 +0700 - ovs-performance - 1998/140085523240704 - extensions/arakoon_installer - 43 - DEBUG - Waiting for cluster localbackend5-abm: available
Feb 10 15:56:06 ovs-performance celery[1954]: 2017-02-10 15:56:06 07700 +0700 - ovs-performance - 1998/140085523240704 - extensions/arakoon_installer - 44 - DEBUG - Started node 172.16.86.136 for cluster localbackend5-abm
Feb 10 15:56:06 ovs-performance celery[1954]: 2017-02-10 15:56:06 19500 +0700 - ovs-performance - 1998/140085523240704 - lib/alba - 45 - INFO - Claimed internally managed arakoon cluster: localbackend5-abm
Feb 10 15:56:06 ovs-performance celery[1954]: 2017-02-10 15:56:06 54100 +0700 - ovs-performance - 1998/140085523240704 - extensions/sshclient - 46 - ERROR - Command "'/usr/bin/alba' 'update-abm-client-config' '--to-json' '--config=arakoon://config/ovs/arakoon/localbackend5-abm/config?ini=%2Fopt%2FOpenvStorage%2Fconfig%2Farakoon_cacc.ini' '--attempts=8'" failed with output "" and error "alba: unknown option `--to-json'.
Feb 10 15:56:06 ovs-performance celery[1954]: 2017-02-10 15:56:06 54200 +0700 - ovs-performance - 1998/140085523240704 - celery/celery.redirected - 48 - WARNING - 2017-02-10 15:56:06 54200 +0700 - ovs-performance - 1998/140085523240704 - extensions/alba-cli - 47 - ERROR - Error: Executing command /usr/bin/alba update-abm-client-config --to-json --config=arakoon://config/ovs/arakoon/localbackend5-abm/config?ini=%2Fopt%2FOpenvStorage%2Fconfig%2Farakoon_cacc.ini --attempts=8 failed with output
Feb 10 15:56:06 ovs-performance celery[1954]: RuntimeError: Executing command /usr/bin/alba update-abm-client-config --to-json --config=arakoon://config/ovs/arakoon/localbackend5-abm/config?ini=%2Fopt%2FOpenvStorage%2Fconfig%2Farakoon_cacc.ini --attempts=8 failed with output
Feb 10 15:56:06 ovs-performance celery[1954]: 2017-02-10 15:56:06 54300 +0700 - ovs-performance - 1998/140085523240704 - celery/celery.redirected - 50 - WARNING - 2017-02-10 15:56:06 54200 +0700 - ovs-performance - 1998/140085523240704 - extensions/alba-cli - 49 - DEBUG - Command: /usr/bin/alba update-abm-client-config --to-json --config=arakoon://config/ovs/arakoon/localbackend5-abm/config?ini=%2Fopt%2FOpenvStorage%2Fconfig%2Farakoon_cacc.ini --attempts=8
Feb 10 15:56:06 ovs-performance celery[1954]: 2017-02-10 15:56:06 54500 +0700 - ovs-performance - 1998/140085523240704 - lib/alba - 52 - ERROR - Failed manual Alba Arakoon checkup during add cluster for backend 407c5740-667e-4a63-a0d4-98cb3474d69d. Executing command /usr/bin/alba update-abm-client-config --to-json --config=arakoon://config/ovs/arakoon/localbackend5-abm/config?ini=%2Fopt%2FOpenvStorage%2Fconfig%2Farakoon_cacc.ini --attempts=8 failed with output
Feb 10 15:56:06 ovs-performance celery[1954]: RuntimeError: Executing command /usr/bin/alba update-abm-client-config --to-json --config=arakoon://config/ovs/arakoon/localbackend5-abm/config?ini=%2Fopt%2FOpenvStorage%2Fconfig%2Farakoon_cacc.ini --attempts=8 failed with output
Feb 10 15:56:06 ovs-performance celery[1954]: 2017-02-10 15:56:06 55100 +0700 - ovs-performance - 1998/140085523240704 - lib/alba - 53 - DEBUG - Removing ALBA backend "localbackend5"
Feb 10 15:56:06 ovs-performance celery[1954]: 2017-02-10 15:56:06 65100 +0700 - ovs-performance - 1954/140085523240704 - celery/celery.worker.job - 80 - ERROR - Task alba.add_cluster[9f34ec9b-fc30-4555-a4df-eecec7b49e77] raised unexpected: RuntimeError('Executing command /usr/bin/alba update-abm-client-config --to-json --config=arakoon://config/ovs/arakoon/localbackend5-abm/config?ini=%2Fopt%2FOpenvStorage%2Fconfig%2Farakoon_cacc.ini --attempts=8 failed with output ',)
Feb 10 15:56:06 ovs-performance celery[1954]: RuntimeError: Executing command /usr/bin/alba update-abm-client-config --to-json --config=arakoon://config/ovs/arakoon/localbackend5-abm/config?ini=%2Fopt%2FOpenvStorage%2Fconfig%2Farakoon_cacc.ini --attempts=8 failed with output

**Comment by kvanhijf** [comment]
Hi,

It seems you have a compatibility problem between your ALBA version and
openvstorage version
Can you please provide us both versions

alba version --terse
> apt-cache policy openvstorage

**Comment by hoanhdo** [comment]
@kvanhijf 
I install and it work

**Comment by hoanhdo** [comment]
@kvanhijf 
this is my version: alba version --terse
1.3.4
