### ISSUE TITLE
Volumedriver fails to steal volume because volume DTL is not in sync while it is

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/volumedriver#267]
In this situation we have 4 nodes with a vPool. The DTL is in sync. 2 Nodes are living in the same domain so between those nodes we are performing HA (Node 2 -> Node 4).
* A vdisk is present on the vpool on node 2
* The vdisk is expected to HA migrate to node 4
* Node 2 is cleanly shutdown
* The vdisk is not being stolen from Node 2 because the DTL is not in sync

@redlicha has the following hypothesis: 
```
* client is connected to .192
* .192 is shut down cleanly -> first the xio server
* client connects to .194, is able to open the volume, redirection between .192 and .194 while the former is not fully down yet. the dtl-in-sync status is not transferred for redirected requests (by default for backward compat purposes, can / should be switched on) -> "false" is assumed. 
* eventually the interprocess comm is also shut down -> stealing is now attempted, but the dtl-in-sync status doesn't allow it
```

Possible solution:
```
* what I think is happening in your test is the above race. So, what you can do is either kill the voldrv (or the complete node) hard
* and/or also set volume_router/vrouter_send_sync_response to 'true' in the config of all nodes. (that one defaults to false for backward compat purposes)

new voldrvs should be able to deal with it, i.e. anything >= 6.3.0 (minus bugs) if the second solution is performed
```

**Comment by redlicha** [comment]
> The vdisk is not being stolen from Node 2 because the DTL is not in sync

"The vdisk is not being stolen from Node 2 because the DTL is not *known to be* in sync", as the `DtlInSync` status is not transferred in the sync response by default.
So either the default value of `volume_router/vrouter_send_sync_response` is changed to true (in which case it needs to be explcitly disabled on setups that have voldrvs < 6.3.0), or the framework needs to set it to `true` explicitly.

**Comment by saelbrec** [comment]
Let's document the backwards compatibility constraint in case of a rolling upgrade from a Fargo <2.7.4 release to RC4 and go ahead with changing the default.

**Comment by redlicha** [comment]
Manual / integration tests succeed after changing the params default value.
