### ISSUE TITLE
I/O request accounted after serviced

### ISSUE THREAD

**Issue by cnanakos** [openvstorage/volumedriver#272]
* I/O thread sends async request
* I/O thread descheduled
* I/O request has already been serviced and freed
* I/O request accounted in the in-flight list by using the old request pointer

**Comment by redlicha** [comment]
The tests under valgrind bumped into the newly introduced control request timeout (triggered by a bug in the tests):
* volume creation in the tests is retried on error to address a race between remote volume creation and startup of the remote; however the number of retries is not limited there
* volume creation in `NetworkServerTest.create_rollback_list_remove_snapshot_remote` succeeded on the remote, but timed out locally
* subsequent volume creation attempts fail b/c the volume exists already
