### ISSUE TITLE
Unable to create vDisks via cloud apis!

### ISSUE THREAD

**Issue by deepshirsath** [openvstorage/volumedriver#276]
We are facing issue while creating vdisk via cloud apis on OVH France **'demostack03'** env.

**OVS node 1** ovs01 --> public ip 178.33.61.6 private ip 172.20.20.1

**workers log**

Feb 24 17:45:57 ovs01 celery[77882]: 2017-02-24 17:45:57 86900 +0100 - ovs01 - 151696/139940545455872 - arakoon_client/pyrakoon - 249251 - ERROR - [Errno 111] Connection refused: Unable to connect to ('172.20.20.1', 26460)
Feb 24 17:45:57 ovs01 celery[77882]: error: [Errno 111] Connection refused
Feb 24 17:45:57 ovs01 celery[77882]: 2017-02-24 17:45:57 86900 +0100 - ovs01 - 151696/139940545455872 - arakoon_client/pyrakoon - 249252 - ERROR - No connection available to node at '172.20.20.1:26460' : Message exchange with node HdC8QGW6PDxBNgIZ failed
Feb 24 17:45:57 ovs01 celery[77882]: 2017-02-24 17:45:57 86900 +0100 - ovs01 - 151696/139940545455872 - arakoon_client/pyrakoon - 249253 - ERROR - No connection available to node at '172.20.20.1:26460': Unable to query node "HdC8QGW6PDxBNgIZ" to look up master
Feb 24 17:46:02 ovs01 celery[77882]: 2017-02-24 17:46:02 44500 +0100 - ovs01 - 151696/139940545455872 - arakoon_client/pyrakoon - 249258 - ERROR - [Errno 111] Connection refused: Unable to connect to ('172.20.20.1', 26460)
Feb 24 17:46:02 ovs01 celery[77882]: error: [Errno 111] Connection refused
Feb 24 17:46:02 ovs01 celery[77882]: 2017-02-24 17:46:02 44600 +0100 - ovs01 - 151696/139940545455872 - arakoon_client/pyrakoon - 249259 - ERROR - [Errno 111] Connection refused: Unable to connect to ('172.20.20.1', 26460)
Feb 24 17:46:02 ovs01 celery[77882]: error: [Errno 111] Connection refused
Feb 24 17:46:02 ovs01 celery[77882]: 2017-02-24 17:46:02 44600 +0100 - ovs01 - 151696/139940545455872 - arakoon_client/pyrakoon - 249260 - ERROR - No connection available to node at '172.20.20.1:26460' : Message exchange with node HdC8QGW6PDxBNgIZ failed
Feb 24 17:46:02 ovs01 celery[77882]: 2017-02-24 17:46:02 44600 +0100 - ovs01 - 151696/139940545455872 - arakoon_client/pyrakoon - 249261 - ERROR - No connection available to node at '172.20.20.1:26460': Unable to query node "HdC8QGW6PDxBNgIZ" to look up master

**OVS node 3** --> public ip  188.165.14.25 private ip 172.20.20.3

Feb 24 17:54:54 ovs03 celery[156265]: 2017-02-24 17:54:54 83000 +0100 - ovs03 - 91687/139803411801856 - lib/vdisk - 250116 - ERROR - Creating new vDisk deva-test-flat_dcc580d2-d241-4c38-b882-fd9f5709c882 failed: failed to send XMLRPC request volumeCreate
Feb 24 17:54:54 ovs03 celery[156265]: 2017-02-24 17:54:54 88500 +0100 - ovs03 - 156265/139803411801856 - celery/celery.worker.job - 250117 - ERROR - Task ovs.vdisk.create_new[7a482f61-f9fb-4aac-a7e8-da86560e21e3] raised unexpected: RuntimeError('failed to send XMLRPC request volumeCreate',)
Feb 24 17:54:54 ovs03 celery[156265]: RuntimeError: failed to send XMLRPC request volumeCreate

Feb 24 18:19:00 ovs03 celery[156265]: RuntimeError: got fault response setMetaDataCacheCapacity

**Comment by cnanakos** [comment]
The above log entries are not related with the volumedriver.
