### ISSUE TITLE
cannot create global backend after create global backend failed

### ISSUE THREAD

**Issue by hoanhdo** [openvstorage/volumedriver#289]
Hi all.
I install openvstorage with these package.
> ii  openvstorage                         2.7.10.1-1                          amd64        openvStorage
ii  openvstorage-backend                 1.7.10.1-1                          amd64        openvStorage Backend plugin
ii  openvstorage-backend-core            1.7.10.1-1                          amd64        openvStorage Backend plugin core
ii  openvstorage-backend-webapps         1.7.10.1-1                          amd64        openvStorage Backend plugin Web Applications
ii  openvstorage-core                    2.7.10.1-1                          amd64        openvStorage core
ii  openvstorage-hc                      1.7.10.1-1                          amd64        openvStorage Backend plugin HyperConverged
ii  openvstorage-sdm                     1.6.10.1-1                          amd64        Open vStorage Backend ASD Manager
ii  openvstorage-webapps                 2.7.10.1-1                          amd64        openvStorage Web Applications

After i create global backend failed. I search issue 
> Creating multiple backends
Creating multiple backends at once fails and leaves the backends in a permanent Installing status.

Then i cannot delete failed backend and create new backend.
How i can create new backend ?.
Thanks

**Comment by kvanhijf** [comment]
Hi,

This is a known issue, for which we haven't had the time to investigate /
fix.
There's 2 solutions:
1) Reinstall and create your backends 1 by 1
2) Check the code and see where exactly it went wrong. Revert everything up
until that point for the failed backend and try again

Sorry for this inconvenience

**Comment by wimpers** [comment]
Hi@hoanhdo

the creating of multiple backends at once should work. There used to be issues when Etcd was selected as distributed config management.  Since we went away from Etcd , we have closed that issue https://github.com/openvstorage/framework/issues/828 . Can you check where it went wrong and let us know. Do create a ticket under https://github.com/openvstorage/framework/issues/ as it will be a framework issue most likely.

**Comment by hoanhdo** [comment]
Hi @wimpers 
I created issue [https://github.com/openvstorage/framework/issues/1543.](url)
It happen some times. I think this issue only vmware but it still physical node.

**Comment by wimpers** [comment]
Closing this one as isn't the correct repo, please continue if issues in  https://github.com/openvstorage/framework/issues/1543 .
