### ISSUE TITLE
Detection of halted (fenced) volumes via Python API

### ISSUE THREAD

**Issue by redlicha** [openvstorage/volumedriver#290]
Scenario:
* volume V is running on instance I
* HA moves V to instance J while I is still alive
=> V will be fenced on I (= put into `halted` state)
.

Depending on which node the Python API connects to, `info_volume` will now either return the volume as `halted` (and owned by `I`) or as healthy (and owned by `J`).

**Comment by wimpers** [comment]
Would be good to fix as otherwise the healthcheck will report false positives.

**Comment by matthiasdeblock** [comment]
Or there can be another check as well in the healthcheck which checks if the volume is running on another volumedriver. And, if the volumedriver is running on another node trigger a WARNING message. If the volume is actually halted (so not running on another node) trigger the CRITICAL (wake up call).

**Comment by redlicha** [comment]
Test: `volumedriver_fs_test`, `PythonClientTest.list_halted_volumes`.

@JeffreyDevloo , assigning this one to you - please close after integration into healthcheck.

**Comment by wimpers** [comment]
Closed by PM.
