### ISSUE TITLE
Support for fast cancellation of background tasks

### ISSUE THREAD

**Issue by redlicha** [openvstorage/volumedriver#298]
Background tasks are handled by a thread pool. Currently, cancellation of such a task has to wait until it's actually scheduled.

**Comment by wimpers** [comment]
Is this related to https://github.com/openvstorage/framework/issues/1530 ?

**Comment by redlicha** [comment]
Only losely:
* in https://github.com/openvstorage/framework/issues/1530 , the slave update is currently being executed and, the transition to master needs to wait for that to finish
* in this case, the transition to master cancels a scheduled update, but the cancellation takes too long

**Comment by redlicha** [comment]
Test: `youtils_test`, `PeriodicActionPoolTest.fast_cancellation`.

**Comment by wimpers** [comment]
Closed by PM.
