### ISSUE TITLE
Expose FileSystemMetadataClient._unlink functionality

### ISSUE THREAD

**Issue by kvanhijf** [openvstorage/volumedriver#304]
The framework would need this functionality to be able to delete directories which have been left over after cleaning out vdisks from the filesystem.

Edit: Another option would be to fix the existing StorageRouterClient.unlink functionality, to allow it to also delete directories

Related ticket: https://github.com/openvstorage/framework/issues/1511

**Comment by redlicha** [comment]
Alternative(?): support removal of directories with the "unlink" call on `StorageRouterClient`.

**Comment by redlicha** [comment]
`StorageRouterClient.unlink` now also allows the removal of empty directories. Test: `volumedriver_fs_test`, `PythonClientTest.rmdir`.
