### ISSUE TITLE
Speed up TLog-written-to-backend callback

### ISSUE THREAD

**Issue by redlicha** [openvstorage/volumedriver#321]
Currently the callback
* marks the tlog as safe on the backend by serializing and uploading a copy of a volume's `SnapshotPersistor`
* marks the tlog as safe locally by serializing a a copy of a volume's `SnapshotPersistor` to a file
* uncorks the metadata entries
* removes entries from the DTL
.

The `SnapshotPersistor` copies are created to avoid interfering (serialization while locking) with the creation of new entries / TLogs in the direct write path. However, at some point the overhead of creating a copy becomes significant as well, impacting write performance.

**Comment by wimpers** [comment]
@redlicha how much work would this be?

**Comment by wimpers** [comment]
Should be solved by https://github.com/openvstorage/volumedriver/issues/332
