### ISSUE TITLE
Expose method to inspect descendants of a volume in ObjectRegistry's Python API

### ISSUE THREAD

**Issue by redlicha** [openvstorage/volumedriver#333]
Debugging helper as the `info_volume` call only provides the reverse mapping (the parent of a volume), and only if the child is running.

**Comment by wimpers** [comment]
@redlicha  Am I correct that this one duplicates https://github.com/openvstorage/volumedriver/issues/164

**Comment by redlicha** [comment]
@wimpers yes, you are.
