### ISSUE TITLE
clone vdisk or vtemplate from other vpool

### ISSUE THREAD

**Issue by hoanhdo** [openvstorage/volumedriver#338]
Hi all.

How i can clone vdisk or vtemplate from one pool to other pool.
I have one pool contain all image, so i want clone vdisk to other vpool.

Thanks.

**Comment by wimpers** [comment]
Hi @hoanhdo ,

cloning between vPools is not possible as vPools can be on separate backends. The easiest way is to copy the .raw files from one vPool to another or use storage vMotion or something similar.
