### ISSUE TITLE
Switch proxy in case of non-connection related errors as well

### ISSUE THREAD

**Issue by redlicha** [openvstorage/volumedriver#341]
Contrary to connection errors, there shall be no blacklisting of the old proxy.

**Comment by redlicha** [comment]
Current proposal: switch on errors other than timeouts.

**Comment by wimpers** [comment]
As summary for my own information:
* On  **connection** error, we switch to another proxy and blacklist the proxy (  https://github.com/openvstorage/volumedriver/issues/336 )
* On **non-connection errors other than timeouts,** we switch to another proxy but don't blacklist. This is added in this ticket.
* On **timeouts**, we don't switch to another proxy or blacklist.

**Comment by redlicha** [comment]
On `non-connection` errors `other than timeouts` proxy switching (without blacklisting) was suggested, no switching on timeouts (@saelbrec , please confirm / correct me).

**Comment by redlicha** [comment]
Related / followed by: #354
