### ISSUE TITLE
Consider using Alba's inline uploads

### ISSUE THREAD

**Issue by redlicha** [openvstorage/volumedriver#347]
https://github.com/openvstorage/alba/blob/master/cpp/include/proxy_sequences.h#L118
* avoid writing temp files for config objects
* allow using remote proxies

for that a download/read counterpart in the proxy client API would be handy (which according to @toolslive exists internally but is not exposed).

**Comment by wimpers** [comment]
@redlicha  Is there any urgency for this or can we assign this to roadmap?

**Comment by redlicha** [comment]
There's no urgency for this, roadmap is fine. The ticket was created to raise awareness for alba offering the feature / possible use cases.

**Comment by wimpers** [comment]
@redlicha what do you see as use case for using a remote proxy (https://github.com/openvstorage/home/issues/38)?

**Comment by wimpers** [comment]
Duplicates https://github.com/openvstorage/volumedriver-ee/issues/47
