### ISSUE TITLE
Edge server workqueue does not fully utilize max number of threads

### ISSUE THREAD

**Issue by redlicha** [openvstorage/volumedriver#357]
The number of threads used by the workqueue (WQ) is adjusted dynamically, based on the number of queued requests. Adding more threads happens by doubling the number up to a configurable maximum. Threads are removed again after a while if the number of queued requests is low.
This might lead to less threads being used than configured, e.g. the following was observed:
* max number of threads: 16
* first burst -> WQ scales up to 16 threads
* idle period, some threads are taken out of service (at the beginning of the next burst)
* second burst -> WQ scales up to 10 threads
.

**Comment by wimpers** [comment]
Milestone closed.
