### ISSUE TITLE
Remove rollback API from python client

### ISSUE THREAD

**Issue by khenderick** [openvstorage/volumedriver#37]
While discussing openvstorage/framework#540 it turned out that doing a rollback can cause issues. We should in that case also clean up that API on the python client.

**Comment by wimpers** [comment]
@redlicha would it make sense to up the 255 clone depth limit?

**Comment by redlicha** [comment]
@wimpers: that's not trivially possible, as it is a design decision that was made in the very early days of volumedriver: clone information is encoded in a single byte (e.g. in the metadata of a volume stored in the MDS / SCO names in the SCO cache / ...).

**Comment by wimpers** [comment]
In that case leave it as is.

**Comment by wimpers** [comment]
After disussion, we will leave the functionality in
