### ISSUE TITLE
backend restart should clean up the correct directories

### ISSUE THREAD

**Issue by jeroenmaelbrancke** [openvstorage/volumedriver#370]
When force restart a particular volume and the directories are still present on the storagerouter the volumedriver will not do a force restart but will try a local restart.

After manually deleting the directories the force restart works.

Could we change this if the force restart is True that the volumedriver check the directories and clean up where necessarily?

**Comment by wimpers** [comment]
@redlicha  is this related to https://github.com/openvstorage/volumedriver/issues/71

or is these directories not related to the metadata?

**Comment by redlicha** [comment]
@wimpers , no, it's unrelated - it's volumedriver internal directories used for caching TLogs etc..

@jeroenmaelbrancke , I understand that you are referring to the `restart_object` call, right? That one is intended to always do a local restart, `force` indicates whether an absent DTL should be ignored or not. For a backend restart the `migrate` call is intended, which however at this point also requires manually moving the metadata and TLog directory out of the way if present. Adding the automatic removal of these local cache directories to the `migrate` call makes most sense IMHO.

**Comment by jeroenmaelbrancke** [comment]
@redlicha Or can you add an extra parameter to the restart_object like the one with stop_object?
With stop_object you have the option to delete the directories also.
How does migrate work if we only want a backend restart on the same storagerouter?

**Comment by wimpers** [comment]
Set to roadmap as there is a workaround (manually move).
