### ISSUE TITLE
documentation about how to install/configure

### ISSUE THREAD

**Issue by despiegk** [openvstorage/volumedriver#41]
we would like to understand how to deploy the components manually
which config files
where are they, what can go in, documentation around it...
how to start them

once we have this then we want to help with some automation around setup & testing

**Comment by despiegk** [comment]
I can't find the docu, its probably just me

**Comment by wimpers** [comment]
All volumedriver info is stored in the GitBook https://openvstorage.gitbooks.io/volumedriver/content/docs/building.html . let me know if the volumedriver build instructuctions are not clear.
