### ISSUE TITLE
edge component documentation

### ISSUE THREAD

**Issue by despiegk** [openvstorage/volumedriver#42]
there seems to be an edge volume driver component
where is it?
can't find it?
how to build?
how to deploy?

**Comment by wimpers** [comment]
@cnanakos can you provide some input around this. Following is what we have around the edge https://openvstorage.gitbooks.io/volumedriver/content/v/d34e4c62a9c2c706f76cd3838851c3c0a17f555a/docs/edge.html

**Comment by cnanakos** [comment]
* Where is it?
Edge is consisted from a client library and a server. The server is part of the volumedriver and is running as a single thread that accepts/dispatches incoming/outgoing I/O and control requests. The library can be installed and used to communicate with the Edge server over TCP/IP or RDMA.

* Can't find it
The Edge client is offered as a different package under the name libovsvolumedriver for the library and libovsvolumedriver-dev for the header file(s). By using the Edge and the offered semantics we support block subsystems for QEMU, blktap and TGT. We also support libvirt, the management tool for managing platform virtualization (KVM in our case).

* How to build it?
The volumedriver build process produces packages for both server and client. If the packages is not the case the building process produces the relevant files, the volumedriver server and the Edge client shared library along with the header file.

* How to deploy?
Deployment of the volumedriver is exactly the same as of today. The same applies for the Edge client which is consisted from a shared library and a header file. The building process provides packages for Ubuntu & CentOS.
