### ISSUE TITLE
Scrubber needs to be configured with correct proxy address

### ISSUE THREAD

**Issue by redlicha** [openvstorage/volumedriver#53]
So far the proxy was bound to localhost but with the RDMA support it'll end up being bound to an RDMA interface, so the scrubber will be fed wrong information.

**Comment by redlicha** [comment]
Fixed in dev, usage info in #61

**Comment by redlicha** [comment]
@pploegaert , are there integration tests that verify the issue is fixed?

**Comment by JeffreyDevloo** [comment]
### Information
Verified due to https://github.com/openvstorage/framework/issues/727 being verified.
