### ISSUE TITLE
Coarse locking during volume creation slows down monitoring / mgmt calls

### ISSUE THREAD

**Issue by redlicha** [openvstorage/volumedriver#62]
While creating a volume, the mgmt mutex to protect the map of volumes is held. Since volume creation can however take long (e.g. in case of backend issues), this impacts mgmt and monitoring calls that also need access to the volume map and hence the lock.
Observed when invoking e.g. `statistics_volumedriver` while at the same time a volume was being created which eventually timed out due to an unrelated error.

Volume creation should hence be modified to use the same mechanism as e.g. volume removal to avoid keeping the lock for prolongued periods.

**Comment by redlicha** [comment]
Also affected: periodic DTL checker.

**Comment by wimpers** [comment]
Closed by PM.
