### ISSUE TITLE
Coarse locking in the periodic DTL checkup slows down monitoring / mgmt

### ISSUE THREAD

**Issue by redlicha** [openvstorage/volumedriver#63]
The mgmt mutex is held while walking over all volumes. In a first step this should be reduced to only holding it while processing a single volume, in a second phase moving it out of the lock should be investigated.

**Comment by wimpers** [comment]
Moved to Gilbert as non SRP.

**Comment by wimpers** [comment]
@redlicha  what is the status of this issue, anything left to do? Any plans in the near future?

**Comment by redlicha** [comment]
Not much work on this one so far just a tentative fix that might improve things. Should be tested again.

**Comment by wimpers** [comment]
Tested by who exactly? Your testing or QA?

**Comment by redlicha** [comment]
QA

**Comment by wimpers** [comment]
@pploegaert  @JeffreyDevloo can you check please

**Comment by wimpers** [comment]
Since Philippe is no longer with us, assigning to @JeffreyDevloo  .

**Comment by redlicha** [comment]
Older than 1 year and the issue hasn't been reported again, so I'm closing this.
