### ISSUE TITLE
build process for Arch linux & ubuntu 16.04

### ISSUE THREAD

**Issue by despiegk** [openvstorage/volumedriver#7]
- build to binary locations (build directory)
- also build the python client for python 2.7

**Comment by dejonghb** [comment]
Note: newer gcc/libboost/... imposes code changes

Build process itself has __3 major steps__:
1. install all __required dependencies__ (cfr. dockerfiles and/or https://github.com/openvstorage/volumedriver/blob/builddocs/doc/manual_building.md)
2. build __volumedriver-buildtools__ (succeeds on ubuntu 16.04)
3. build __volumedriver__ (requires code changes; code must remain buildable on centos-7 as well)

**Comment by dejonghb** [comment]
Branches created for the changed codebase...
- on **volumedriver-buildtools**
  - *feature/archlinux* (for Dockerfile et al for Arch Linux)
  - *feature/ubu1604* (for Dockerfile et al for Ubuntu 16.04)
- on **volumedriver** use *feature/ubuntu-16.04* for both Ubuntu 16.04 & Arch Linux

**Comment by despiegk** [comment]
@redlicha how much time is required to do the changes in vol driver?

**Comment by saelbrec** [comment]
Builds succeed but tests are bailing out, currently it's not clear if this requires changes in the code or only in how the tests inside the docker image are being executed. First assessment is that further investigation and possible fix would require 1 or 2 days.

**Comment by redlicha** [comment]
@despiegk the bulk of the required changes is present in the branches mentioned by @dejonghb . There are however failing / crashing tests in the CI builds we created for Ubuntu 16.04 and Arch Linux that prevent merging these back. A rough estimate for debugging / fixing is +/- 1 day.
@saelbrec: once these issues are sorted out there's still the question on how to support (if at all?) the two Ubuntu LTS flavours - do we release specific packages for each?

**Comment by dejonghb** [comment]
ubuntu 16.04 branches were merged into dev branch

**Comment by dejonghb** [comment]
everything got merged into the dev branches

**Comment by despiegk** [comment]
can we now build?
are there procedures?

**Comment by wimpers** [comment]
As discussed last Friday with @despiegk  Arch Linux isn't required.

**Comment by pploegaert** [comment]
PASSED:

docker file serves as doc according to @redlicha:
https://github.com/openvstorage/volumedriver-buildtools/tree/dev/docker/ubuntu1604

jenkins build results:
http://10.100.129.100:8080/view/volumedriver/view/ubuntu/job/volumedriver-dev-release-ubuntu-16.04/

Please reopen if this is considered incomplete - thx
