### ISSUE TITLE
Redirected volume removal times out and leaves stale metadata

### ISSUE THREAD

**Issue by redlicha** [openvstorage/volumedriver#71]
Scenario:
- config:
  - redirect timeout 5 secs
  - backend timeout 15 secs
  - volume V is running on node N
- SCO write W to the backend is happening in the background
- volume removal is started on node M -> redirect to node N, removal needs to wait for W to finish
- W encounters backend issues, finishes (unsuccessfully) when the backend timeout fires
  => unlink call times out on N

**Comment by redlicha** [comment]
Parameter tuning can alleviate this issue, a proper fix would however be a deferred removal in the background by a garbage collection component e.g. based on arakoon.

**Comment by wimpers** [comment]
@redlicha  can this one be closed?

**Comment by wimpers** [comment]
From Arne

> 
> I think there wasn't really any work on the voldrv side for it
> i.e. the issue is still there
> might be that it's not triggered anymore at the moment

**Comment by redlicha** [comment]
The original issue still exists. A possible solution would be a garbage collector.

**Comment by wimpers** [comment]
Decision from BAM:
* HC should report on stale metadata (https://github.com/openvstorage/openvstorage-health-check/issues/379)
* OPS needs to cleanup (https://github.com/openvstorage/dev_ops/issues/93)
