### ISSUE TITLE
Virsh tries to autostart vms before volume driver has started

### ISSUE THREAD

**Issue by JeffreyDevloo** [openvstorage/volumedriver#84]
## Problem description
Virsh tries to autostart vms before volume driver has started
virsh log: 
```
2016-08-12 17:25:39.103+0000: 1827: error : qemuAutostartDomain:292 : Failed to autostart VM 'ubuntu14.04': Failed to open file '/mnt/vm-vpool/ubuntu.raw': No such file or directory
```
Volumedriver log:
```
2016-08-12 17:25:40 729058 +0200 - ovs-node1 - 2809/0x00007f27d023b940 - volumedriverfs/VolManager - 000000000000000f -  info - start: Initializing: should only happen on startup or in the testers
```
As you can see, virsh logged its error a second before the volume driver has started.
## Possible root of the problem
The libvirtd service doesnt wait for the volumedriver to finish. (The startup condition cant be modified to wait for this change aswell)
## Temporary solution
Added a sleep of five seconds (the error occurs within a span of two seconds for me) to the pre start script.
## Possible solution
Unknown
### Setup

Hyperconverged setup

- Three nodes with each three disks for the back-end

### Package information

- openvstorage                       2.7.2-rev.3859.42b3488-1	amd64        openvStorage
- openvstorage-backend               1.7.2-rev.675.37ca5b8-1	amd64        openvStorage Backend plugin
- openvstorage-backend-core          1.7.2-rev.675.37ca5b8-1	amd64        openvStorage Backend plugin core
- openvstorage-backend-webapps       1.7.2-rev.675.37ca5b8-1	amd64        openvStorage Backend plugin Web Applications
- openvstorage-cinder-plugin         1.2.2-rev.32.948a8c1-1	amd64        OpenvStorage Cinder plugin for OpenStack
- openvstorage-core                  2.7.2-rev.3859.42b3488-1	amd64        openvStorage core 
- openvstorage-hc                    1.7.2-rev.675.37ca5b8-1	amd64        openvStorage Backend plugin HyperConverged
- openvstorage-health-check          2.0.0-rev.117.3212ea9-1	amd64        Open vStorage HealthCheck
- openvstorage-sdm                   1.6.2-rev.330.f06c8de-1	amd64        Open vStorage Backend ASD Manager
- openvstorage-test                  2.7.2-rev.980.0dbc80f-1	amd64        openvStorage autotest suite
- openvstorage-webapps               2.7.2-rev.3859.42b3488-1	amd64        openvStorage Web Applications

**Comment by redlicha** [comment]
The order in which services are started is not something volumedriver is concerned with. @wimpers, can you please move this to an appropriate place?
