### ISSUE TITLE
StorageRouterClient should expose a timeout

### ISSUE THREAD

**Issue by kvanhijf** [openvstorage/volumedriver#87]
When establishing a storagerouterclient object with a ClusterContact with an incorrect port (used for something else), the client connection doesn't time out, while it should

Snippet:
from volumedriver.storagerouter.storagerouterclient import StorageRouterClient, ClusterContact
contact = ClusterContact('10.100.193.154', 26202)
client = StorageRouterClient('23cb2f8f-bef4-43b9-95d3-3db7026cf3c0', [contact])
client.server_revision()  --> this call never returns

The problem in above snippet is port 26202. This should have been 26201 because 26202 is used for DTL traffic
The client object can be created, but every call just makes the process hang

**Comment by redlicha** [comment]
The constructors of `{Local,StorageRouter}Client` now accept an optional client timeout argument (in seconds), which can also be queried via the `client_timeout_secs` method.

**Comment by kinvaris** [comment]
PASSED:

**Scenario 1:** no timeout is introduced, issue is observed
```
In [1]: from volumedriver.storagerouter.storagerouterclient import StorageRouterClient, ClusterContact

In [7]: contact = ClusterContact('10.100.199.161', 26202)

In [8]: client = StorageRouterClient('3067b5fc-ecdc-4ee4-8cf1-d6fdedbde96f', [contact])

In [9]: client.server_revision() --> does not return
```

**Scenario 1:** 5 second timeout is introduced, solution is observed
```
In [1]: from volumedriver.storagerouter.storagerouterclient import StorageRouterClient, ClusterContact

In [7]: contact = ClusterContact('10.100.199.161', 26202)

In [8]: client = StorageRouterClient('3067b5fc-ecdc-4ee4-8cf1-d6fdedbde96f', [contact], 5)

In [9]: client.server_revision()
---------------------------------------------------------------------------
ClusterNotReachableException              Traceback (most recent call last)
<ipython-input-9-95b9c982717b> in <module>()
----> 1 client.server_revision()

ClusterNotReachableException:  
```

As seen in the docstring:
```
In [3]: client = StorageRouterClient?
Type:       class
String Form:<class 'volumedriver.storagerouter.storagerouterclient.StorageRouterClient'>
File:       /usr/lib/python2.7/dist-packages/volumedriver/storagerouter/storagerouterclient.so
Docstring:  client for management and monitoring of a volumedriverfs cluster
Constructor information:
 Docstring:
    __init__( (object)arg1, (str)vrouter_cluster_id, (object)cluster_contacts [, (object)client_timeout_secs=None]) -> None :
        Create a client interface to a volumedriverfs cluster
        @param vrouter_cluster_id: string, cluster_id 
        @param cluster_contacts: [ClusterContact] contact points to the cluster
        @param client_timeout: unsigned, optional client timeout (seconds)
```
