### ISSUE TITLE
Python API + qemu package should expose the volume extend functionality

### ISSUE THREAD

**Issue by kvanhijf** [openvstorage/volumedriver#89]
As discussed with @saelbrec , the decision has been made that extending a volume should both be possible using the API and qemu directly. Currently this is not possible in any way

stack@devstack:/opt/devstack$ qemu-img resize -f raw openvstorage+tcp:10.100.193.154:26203/test +20G
qemu-img: This image does not support resize

**Comment by wimpers** [comment]
Edge side still todo.

**Comment by cnanakos** [comment]
@wimpers  Edge already supports volume resizing. Probably the QEMU package being used is not the latest one from unstable.

**Comment by wimpers** [comment]
@redlicha so if you merge your PR this is can be set to fixed?

**Comment by redlicha** [comment]
@wimpers: correct. FWIW, the PR was just merged into dev.

**Comment by redlicha** [comment]
Feature implemented.
