### ISSUE TITLE
Fusemount refused to unmount

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/volumedriver#92]
When creating a new environment in most cases we use this wiper to clean the environment: https://github.com/openvstorage/dev_ops/blob/master/Bash/OpenvSwiper.sh

After doing this on a GIG environment, we noticed that the vpool mountpoint was still present with `Transport Endpoint Not Connected`. After digging through `lsof` and trying some other stuff we failed to unmount the mountpoint. 

After getting the issue twice, we tried `lazy unmount with umount` and it worked.

**Comment by wimpers** [comment]
@kinvaris can we add this to the swiper steps and document under the voldrv troubleshooting section in the voldrv gitbook?

**Comment by kinvaris** [comment]
Added to volumedriver documentation: https://github.com/openvstorage/volumedriver/pull/175
